### ISSUE TITLE
Error: Not ready yet

### ISSUE THREAD

**Issue by TheEssem** [TheEssem/esmBot#1]
This error occurs when attempting to play a soundboard command while another one is playing. Still haven't found a proper way to check if the connection is ready without significant playback changes.

```
Error: Not ready yet
    at VoiceConnection.play (/mnt/d/files/esmbot-rewrite/node_modules/eris/lib/voice/VoiceConnection.js:430:19)
    at module.exports (/mnt/d/files/esmbot-rewrite/utils/soundplayer.js:15:16)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

**Comment by TheEssem** [comment]
I've added a workaround for this in commit ba4ded7, however I still think that a method that makes it use the previous behavior would be nice.

**Comment by TheEssem** [comment]
Reopening as this issue is continuing to happen in some cases.

**Comment by TheEssem** [comment]
This issue has been occurring less often lately (probably due to a fix in Eris or a commit in the bot), closing this again until further notice.
