### ISSUE TITLE
Speed Error

### ISSUE THREAD

**Issue by LooksLikeIveLost** [TheEssem/esmBot#4]
`Message: TypeError: Cannot read property 'length' of undefined

Stack Trace: TypeError: Cannot read property 'length' of undefined
    at exports.run (/root/esmBot/commands/speed.js:23:72)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Client.module.exports (/root/esmBot/events/messageCreate.js:52:20)`

This error occurred when performing the command "speed" to a gif until it consisted of seemingly one still frame, then performing the command again, giving the error.

**Comment by TheEssem** [comment]
Fixed with https://github.com/TheEssem/esmBot/commit/56b382fce3cf246fe9c20403ff51561d3ff86d49, will be implemented in 1.2.8
