### ISSUE TITLE
Error with screenshot command

### ISSUE THREAD

**Issue by Jack5079** [TheEssem/esmBot#6]
The error:
```
Message: FetchError: request to http://172.17.0.2:9222/json/version failed, reason: connect EHOSTUNREACH 172.17.0.2:9222

Stack Trace: FetchError: request to http://172.17.0.2:9222/json/version failed, reason: connect EHOSTUNREACH 172.17.0.2:9222
    at ClientRequest.<anonymous> (/root/esmBot/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:432:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
Command ran: `&screenshot https://5079.ml/is-pp-emoji-censored/`

**Comment by TheEssem** [comment]
Seems to be fixed with 119fd36
