### ISSUE TITLE
Error: spawn ENOMEM

### ISSUE THREAD

**Issue by Jaguar-515** [TheEssem/esmBot#7]
Tried using &speed on a gif, got this:

error.txt:
```
Message: Error: spawn ENOMEM

Stack Trace: Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:405:11)
    at spawn (child_process.js:548:9)
    at Object.execFile (child_process.js:232:17)
    at exec (child_process.js:153:25)
    at child_process.js:167:29
    at typeCheck (/root/esmBot/utils/imagedetect.js:29:40)
    at async module.exports (/root/esmBot/utils/imagedetect.js:50:22)
    at async exports.run (/root/esmBot/commands/speed.js:11:17)
    at async Client.module.exports (/root/esmBot/events/messageCreate.js:45:20)
```

**Comment by TheEssem** [comment]
duplicate of #5
